// examples/nextjs-example/src/components/PreviewWrapper.tsx
/**
 * Hygraph Preview wrapper for Next.js App Router
 * Minimal setup for content preview integration
 */

'use client';

import { useRouter } from 'next/navigation';
import dynamic from 'next/dynamic';

interface PreviewWrapperProps {
  children: React.ReactNode;
}

// Dynamically import to avoid SSR issues
const HygraphPreview = dynamic(
  async () => {
    const { HygraphPreview } = await import('@hygraph/preview-sdk/react');
    return { default: HygraphPreview };
  },
  { ssr: false }
);

export function PreviewWrapper({ children }: PreviewWrapperProps) {
  const router = useRouter();

  // Only enable in development
  if (process.env.NODE_ENV !== 'development') {
    return <>{children}</>;
  }

  return (
    <HygraphPreview
      endpoint={process.env.NEXT_PUBLIC_HYGRAPH_ENDPOINT!}
      studioUrl={process.env.NEXT_PUBLIC_HYGRAPH_STUDIO_URL}
      debug={true}
      onSave={() => {
        console.log('Content saved, refreshing...');
        router.refresh();
      }}
      sync={{
        fieldFocus: true,
      }}
    >
      {children}
    </HygraphPreview>
  );
}

// examples/vue-example/src/components/PreviewWrapper.vue
<template>
  <div>
    <slot />
  </div>
</template>

<script setup lang="ts">
import { onMounted, onUnmounted } from 'vue'
import { useRouter } from 'vue-router'

const router = useRouter()
let preview: { destroy: () => void; subscribe: (event: string, options: { callback: () => void }) => void } | null = null

onMounted(async () => {
  // Only load in development
  if (import.meta.env.DEV && import.meta.env.VITE_HYGRAPH_ENDPOINT) {
    try {
      const { Preview } = await import('@hygraph/preview-sdk/core')

      preview = new Preview({
        endpoint: import.meta.env.VITE_HYGRAPH_ENDPOINT,
        studioUrl: import.meta.env.VITE_HYGRAPH_STUDIO_URL,
        debug: true,
      })

      // Refresh page on save
      preview.subscribe('save', {
        callback: () => {
          console.log('Content saved, refreshing...')
          router.go(0)
        }
      })
    } catch (error) {
      console.warn('Could not load Hygraph Preview:', error)
    }
  }
})

onUnmounted(() => {
  if (preview) {
    preview.destroy()
    preview = null
  }
})
</script>
