// examples/vue-example/src/components/PreviewWrapper.vue
<template>
  <div>
    <slot />
  </div>
</template>

<script setup lang="ts">
import { onMounted, onUnmounted } from 'vue'
import { useRouter } from 'vue-router'

const router = useRouter()
let preview: { destroy: () => void; subscribe: (event: string, options: { callback: () => void }) => void } | null = null

onMounted(async () => {
  // Only load in development
  if (import.meta.env.DEV && import.meta.env.VITE_HYGRAPH_ENDPOINT) {
    try {
      const { Preview } = await import('@hygraph/preview-sdk/core')

      preview = new Preview({
        endpoint: import.meta.env.VITE_HYGRAPH_ENDPOINT,
        studioUrl: import.meta.env.VITE_HYGRAPH_STUDIO_URL,
        debug: true,
      })

      // Refresh page on save
      preview.subscribe('save', {
        callback: () => {
          console.log('Content saved, refreshing...')
          router.go(0)
        }
      })
    } catch (error) {
      console.warn('Could not load Hygraph Preview:', error)
    }
  }
})

onUnmounted(() => {
  if (preview) {
    preview.destroy()
    preview = null
  }
})
</script>

// examples/nextjs-pages-example/components/PreviewWrapper.tsx
import { useRouter } from 'next/router';
import { useEffect, useState, useMemo, useLayoutEffect } from 'react';
import type { ComponentType, ReactNode } from 'react';

interface PreviewWrapperProps {
  children: ReactNode;
}

export function PreviewWrapper({ children }: PreviewWrapperProps) {
  const router = useRouter();
  const [PreviewComponent, setPreviewComponent] = useState<ComponentType<any> | null>(null);
  const [isMounted, setIsMounted] = useState(false);

  // Use useLayoutEffect to ensure React is fully initialized before loading SDK
  useLayoutEffect(() => {
    setIsMounted(true);
  }, []);

  useEffect(() => {
    // Only proceed if mounted and in development
    if (!isMounted || process.env.NODE_ENV !== 'development') return;

    // Load SDK module
    import('@hygraph/preview-sdk/react')
      .then((mod) => {
        setPreviewComponent(() => mod.HygraphPreview);
      })
      .catch((error) => {
        console.error('Failed to load Hygraph Preview SDK:', error);
      });
  }, [isMounted]);

  const handleSave = useMemo(() => {
    return () => {
      console.log('Content saved, refreshing...');
      router.replace(router.asPath);
    };
  }, [router]);

  // Don't render Preview until mounted and component is loaded
  if (!isMounted || !PreviewComponent || process.env.NODE_ENV !== 'development') {
    return <>{children}</>;
  }

  return (
    <PreviewComponent
      endpoint={process.env.NEXT_PUBLIC_HYGRAPH_ENDPOINT}
      studioUrl={process.env.NEXT_PUBLIC_HYGRAPH_STUDIO_URL}
      debug={true}
      onSave={handleSave}
    >
      {children}
    </PreviewComponent>
  );
}
